### ISSUE TITLE
Issue gbdx env creation

### ISSUE THREAD

**Issue by grizonnetm** [GeoBigData/gbdx-training#5]
Following the instructions to configure the env for foss4g tutorial, I've got an issue related to the creation of te

I'm on ubuntu 16.04 64 bits.

See the traceback below:

bin/conda env create -f ~/anaconda2/gbdxtools_env.yml 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.9.1
       root environment : /home/grizonnetm/anaconda2  (writable)
    default environment : /home/grizonnetm/anaconda2
       envs directories : /home/grizonnetm/anaconda2/envs
                          /home/grizonnetm/.conda/envs
          package cache : /home/grizonnetm/anaconda2/pkgs
                          /home/grizonnetm/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : /home/grizonnetm/.netrc
           offline mode : False
             user-agent : conda/4.3.24 requests/2.9.1 CPython/2.7.13 Linux/4.4.0-91-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ bin/conda-env create -f /home/grizonnetm/anaconda2/gbdxtools_env.yml`

    Traceback (most recent call last):
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 53, in get_single_node
        document = self.compose_document()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/composer.py", line 76, in compose_document
        self.get_event()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 136, in get_event
        self.current_event = self.state()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/parser.py", line 215, in parse_document_end
        token = self.peek_token()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 239, in fetch_more_tokens
        return self.fetch_value()
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/ruamel_yaml/scanner.py", line 598, in fetch_value
        self.get_mark())
    ScannerError: mapping values are not allowed here
      in "<byte string>", line 421, column 56:
         ... -destination-box" style="display: none;">

**Comment by dangetman** [comment]
@grizonnetm, I believe this occurs when the yml file has copy/paste text errors (additional spaces and the like). This should not occur when you pull the repository and use the file directly, but may occur if the text from the yml file is copied and pasted from the raw view on github or downloaded in some other way.

I'm happy to help address this issue if pulling the file does not resolve the problem.

**Comment by grizonnetm** [comment]
Thanks for your answer, cloning the repo solved this issue but I've got now an other error which occur at the end of the env creation related to the retrying package. Note that I've iupdated conda before the env creation following instructions in the README.

Please find the error message below:

+ /home/grizonnetm/anaconda2/envs/gbdxtools/bin/python -m nb_conda_kernels.install --enable --prefix=/home/grizonnetm/anaconda2/envs/gbdxtools
Enabling nb_conda_kernels...
Enabled nb_conda_kernels

+ /home/grizonnetm/anaconda2/envs/gbdxtools/bin/jupyter-nbextension enable nb_conda --py --sys-prefix
Enabling notebook extension nb_conda/main...
      - Validating: OK
Enabling tree extension nb_conda/tree...
      - Validating: OK
+ /home/grizonnetm/anaconda2/envs/gbdxtools/bin/jupyter-serverextension enable nb_conda --py --sys-prefix
Enabling: nb_conda
- Writing config: /home/grizonnetm/anaconda2/envs/gbdxtools/etc/jupyter
    - Validating...
      nb_conda  OK

Traceback (most recent call last):
  File "/home/grizonnetm/anaconda2/envs/gbdxtools/bin/pip", line 4, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 30, in <module>
    from pip._vendor.retrying import retry
ImportError: No module named retrying
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.9.1
       root environment : /home/grizonnetm/anaconda2  (writable)
    default environment : /home/grizonnetm/anaconda2
       envs directories : /home/grizonnetm/anaconda2/envs
                          /home/grizonnetm/.conda/envs
          package cache : /home/grizonnetm/anaconda2/pkgs
                          /home/grizonnetm/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : /home/grizonnetm/.netrc
           offline mode : False
             user-agent : conda/4.3.24 requests/2.9.1 CPython/2.7.13 Linux/4.4.0-91-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ bin/conda-env create -f /home/grizonnetm/software/gbdx/src/gbdx-training/workshop_prep/gbdxtools_env.yml`




    Traceback (most recent call last):
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "/home/grizonnetm/anaconda2/lib/python2.7/site-packages/conda_env/pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/home/grizonnetm/anaconda2/lib/python2.7/subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '[u'/home/grizonnetm/anaconda2/envs/gbdxtools/bin/python', u'/home/grizonnetm/anaconda2/envs/gbdxtools/bin/pip', '-V']' returned non-zero exit status 1

**Comment by grizonnetm** [comment]
I had an issue with existing PYTHONPATH I think. It works now, thanks again.
